"""Mode/DO panel (same as teleop_gui.py) plus a pilot-study trial runner
driven by "Pilot_Study.xlsx" (pilot_data/, generated by build_workbook_v3.py):
auto mode-switching per trial,
start/stop/redo recordings, and on-screen tumor location / peg transfer
setup info so you can prep the physical task correctly before each trial.

Must be run FROM INSIDE the embedded IRE IPython shell (dvrk_system -e
IRE_IPYTHON), NOT as a separate process -- mtsManagerLocal.GetInstance()
only sees components living in its own process:

    %run study_gui.py
    # or: exec(open('study_gui.py').read())

Tkinter's mainloop runs in a background thread so the IPython prompt stays
usable while the window is open. `ros2 bag record` runs as its own OS
subprocess (non-blocking Popen), not a Python thread -- there is no polling
thread for it; Stop/Abort act on the Popen handle directly.

Close "Pilot_Study.xlsx" in Excel/LibreOffice before running a
session: this reads the trial plan once at session start and writes results
back after each trial, but a spreadsheet app with the file open doesn't see
those external writes and can silently overwrite them if you save there
mid-session. The GUI shows everything you need (mode, trial #, tumor
location / peg config) so you shouldn't need the sheet open at all while
running.
"""
import datetime
import os
import shutil
import signal
import subprocess
import threading
import time
import tkinter as tk
from tkinter import filedialog, messagebox, ttk

import cisstMultiTaskPython as mts
from cisstMultiTaskPython import mtsStdString, mtsBool, MTS_NOT_BLOCKING
import openpyxl

COMPONENT_NAME = 'MTMR_PSM2'

# the four study conditions, keyed by the pilot Excel's "Mode Code" column
# (see build_workbook_v3.py / ReadMe sheet in Pilot_Study.xlsx) -- applied
# both by the manual buttons below and by TrialSession.set_mode_for_current()
# during an Excel-driven session, so one definition drives both. BIL_ON and
# BIL_OFF both drive the same underlying teleop_mode ("bilateral") and only
# differ in DO state, so this used to be impossible to express as a single
# "teleop_mode -> DO" policy dict (that was the old MODE_MAP/MODE_DO_POLICY
# split) -- now each condition carries its own explicit (teleop_mode, do_on)
# pair instead.
STUDY_CONDITIONS = {
    'UNI':     ('unilateral', False),
    'BIL_OFF': ('bilateral',  False),
    'BIL_ON':  ('bilateral',  True),
    'CSB':     ('contact',    False),
}

EXCEL_PATH = '/home/ndrakes1/pilot_data/Pilot_Study.xlsx'
DATA_ROOT = '/home/ndrakes1/pilot_data'

# raw is whatever dvrk_video's gscam launch publishes (started separately,
# by hand, same as always -- this GUI doesn't manage that process); the
# compressed topic only has data while the relay below is running, but it's
# safe to always list it in TOPICS regardless -- `ros2 bag record` just
# records nothing for a topic with no publisher, same as any other signal
# that happens to be inactive for a given trial
RAW_VIDEO_TOPIC = '/decklink/image_raw'
COMPRESSED_VIDEO_TOPIC = '/decklink/image_raw/compressed'
THEORA_VIDEO_TOPIC = '/decklink/image_raw/theora'

# image_transport plugin name -> (bag topic, ros2 run image_transport republish
# 2nd positional arg). Theora is an actual inter-frame video codec (exploits
# redundancy between frames, not just within one), so for a mostly-static
# surgical scene it compresses substantially smaller than JPEG-per-frame at
# comparable visual quality -- confirmed installed and registered
# (`ros2 run image_transport list_transports` lists `image_transport/theora`,
# provided by the `theora_image_transport` package). Kept jpeg as an option
# since it's the simpler/more universally-playable format if that ever matters
# more than size.
VIDEO_TRANSPORTS = {
    'theora (recommended)': ('theora', THEORA_VIDEO_TOPIC),
    'jpeg': ('compressed', COMPRESSED_VIDEO_TOPIC),
}
DEFAULT_VIDEO_TRANSPORT = 'theora (recommended)'

# theora's own header/setup packets (b_o_s=1) are only ever emitted ONCE, at
# encoder startup -- NOT resent to late subscribers (DDS durability on the
# topic is VOLATILE, confirmed live). A relay left running across multiple
# trials means only the FIRST trial recorded after it starts actually
# captures those header packets -- every trial after that has a theora
# stream with no headers at all, which no theora decoder (ROS or otherwise)
# can make sense of. Found this the hard way: P01_S2_BIL_T02/T04/UNI_T03 and
# a redone P01_S2_CSB_T01 all came back with first_packetno in the
# 3600-3700s and zero b_o_s packets -- their video tracks are unrecoverable
# (the one bag that did have the headers was overwritten by a same-stem
# redo), though the actual kinematic/force topics in those bags are
# untouched and fine.
#
# Fixed at the source, not worked around: TrialSession.start_trial() now
# restarts VideoRelay fresh for every trial (bag record first, then the
# relay restart, so the recorder's subscription is already live when the
# new encoder's headers go out -- see the comment in start_trial()).
# Verified for real: restarted the relay against the live feed and
# confirmed via `ros2 topic echo --field b_o_s` that the first packet after
# a restart is a real header packet, then recorded+decoded a test bag
# through the exact same ordering used here and it decoded clean. jpeg is
# kept as a fallback -- it has no bootstrapping requirement at all, so it's
# worth reaching for only if a session-specific issue ever breaks the
# restart-per-trial guarantee (e.g. RAW_VIDEO_TOPIC not up yet at trial
# start) and there's no time to debug it mid-session.

TOPICS = [
    '/PSM2/measured_js', '/PSM2/setpoint_js', '/PSM2/measured_cp', '/PSM2/measured_cv', '/PSM2/body/measured_cf',
    '/MTMR/measured_js', '/MTMR/setpoint_js', '/MTMR/measured_cp', '/MTMR/measured_cv', '/MTMR/body/measured_cf',
    '/measured_cf',
    # both listed regardless of which transport is actually running this
    # session -- `ros2 bag record` just records nothing for a topic with no
    # publisher, same as any other signal that happens to be inactive
    COMPRESSED_VIDEO_TOPIC,
    THEORA_VIDEO_TOPIC,
]

STUDY_SHEET = {1: 'Study1_Palpation', 2: 'Study2_PegTransfer'}
SETUP_INFO_LABEL = {1: 'Tumor Location', 2: 'Peg Transfer Configuration'}

# fixed column positions -- same in both sheets in "Pilot_Study.xlsx"
# (Completed, Participant ID, Trial #, Mode Name, <setup info>, ..., Rosbag
# Filename, Session Date, Notes, Mode Code)
COL_COMPLETED, COL_PARTICIPANT, COL_TRIAL_NUM, COL_MODE_NAME, COL_SETUP_INFO = 1, 2, 3, 4, 5
COL_MODE_CODE = 12

# NOTE: there IS a "Rosbag Filename" column (9) in both sheets -- in the
# current workbook (build_workbook_v3.py) it's a live Excel formula
# (e.g. `=B2&"_S2_"&L2&"_T"&TEXT(C2,"00")`), but openpyxl's data_only=True
# only ever returns a formula's last-CACHED value, which requires Excel
# itself to have opened+saved the file at least once -- until that happens
# it reads back as a plain empty cell, indistinguishable from the older
# workbook where this column was never populated at all (that's what "has
# no rosbag filename" errors came from: _bag_path_for() used to read that
# cell directly and blow up whenever it read blank). Fixed by computing the
# stem in Python instead of trusting that cell either way -- see
# _make_stem() below, which reproduces the exact same naming convention the
# formula encodes (confirmed by reading the formula text, not just its
# cached value).

# result columns 6/7/8/10/11 mean different things per sheet (e.g. study1's
# "Participant Response"/"Correct?" vs study2's "Completion Time (s)"/
# "Dropped Peg Count"), but sit at the same positions in both -- these are
# outcomes of *running* a trial (whether logged by this tool or typed in by
# hand afterward), so redo_trial() clears all of them, not just what this
# tool itself wrote. Column 9 (Rosbag Filename) and the plan columns
# (2/3/4/5/12) are deliberately excluded -- those are the trial plan, not a
# result, and stay untouched by a redo.
OUTCOME_COLUMNS = [6, 7, 8, 10, 11]

BAG_PATH_COL_HEADER = 'Actual Bag Path'
RECORDED_AT_COL_HEADER = 'Recorded At (UTC)'


def _make_stem(participant, study, mode_code, trial_num):
    if mode_code is None:
        # matches the workbook's own formula for warm-up rows exactly:
        # `=B2&"_S1_WARMUP"` -- all caps, no trial number suffix
        return f'{participant}_S{study}_WARMUP'
    return f'{participant}_S{study}_{mode_code}_T{int(trial_num):02d}'


def _connect():
    manager = mts.mtsManagerLocal.GetInstance()
    component = manager.GetComponent(COMPONENT_NAME)
    if component is None:
        raise RuntimeError(
            f'component "{COMPONENT_NAME}" not found in this process -- '
            'run this from inside the IRE shell dvrk_system was started '
            'with, not a separate script/process'
        )
    teleop = component.GetInterfaceProvided('Setting').GetEndUserInterface('study_gui')
    return {
        'set_mode': teleop.GetCommandWrite('set_teleop_mode'),
        'get_mode': teleop.GetCommandRead('teleop_mode'),
        'set_psm_do': teleop.GetCommandWrite('set_psm_disturbance_observer'),
        'set_mtm_do': teleop.GetCommandWrite('set_mtm_disturbance_observer'),
    }


def _read_mode(cmds):
    try:
        result = mtsStdString()
        cmds['get_mode'].Execute(result)
        data = result.GetData()
        if not isinstance(data, str):
            data = str(data)
        if 'Swig Object' in data or 'proxy of' in data:
            # this binding's GetData() didn't come back as a real Python
            # string -- report unknown rather than a bogus value that would
            # fail every comparison against it (this is exactly what caused
            # "teleop_mode verify failed ... read back <Swig Object ...>")
            raise ValueError(f'GetData() returned non-string-like data: {data!r}')
        return data
    except Exception as exc:
        print(f'study_gui: could not read current mode ({exc})')
        return '(unknown)'


class VideoRelay:
    """Manages one `image_transport republish` subprocess (raw -> a
    compressed transport, see VIDEO_TRANSPORTS). TrialSession.start_trial()
    calls restart() on this at the start of every trial -- theora's header
    packets are only ever emitted once, at encoder startup, so a relay left
    running across multiple trials produces every-trial-after-the-first
    with no headers at all (found the hard way, see the comment above
    VIDEO_TRANSPORTS). Restarting fresh per trial means each trial's own
    bag always contains its own encoder's startup, headers included --
    harmless overhead for jpeg, which has no such bootstrap requirement.
    Does not manage dvrk_video's own gscam launch, which publishes
    RAW_VIDEO_TOPIC -- start that yourself, separately, same as always."""

    def __init__(self):
        self._proc = None
        self.transport = None   # plugin name of whatever is currently running

    def running(self):
        return self._proc is not None and self._proc.poll() is None

    def start(self, transport_label):
        if self.running():
            return
        plugin, out_topic = VIDEO_TRANSPORTS[transport_label]
        cmd = ['ros2', 'run', 'image_transport', 'republish', 'raw', plugin,
               '--ros-args',
               '-r', f'in:={RAW_VIDEO_TOPIC}',
               '-r', f'out/{plugin}:={out_topic}']
        self._proc = subprocess.Popen(cmd, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                                       stderr=subprocess.PIPE, preexec_fn=os.setsid)
        self.transport = plugin
        # republish's stderr otherwise sits in an unread pipe -- if the
        # command itself is wrong (bad remap syntax, missing plugin, etc.)
        # it exits almost immediately, and without this check the GUI would
        # keep reporting "running" for a process that's already dead,
        # silently recording nothing (exactly the "count: 0" symptom)
        time.sleep(0.5)
        returncode = self._proc.poll()
        if returncode is not None:
            _, stderr = self._proc.communicate()
            self._proc = None
            self.transport = None
            raise RuntimeError(
                f'republish exited immediately (code {returncode}):\n'
                f'{stderr.decode(errors="replace").strip()[-800:]}'
            )

    def stop(self):
        if self._proc is None:
            return
        pgid = os.getpgid(self._proc.pid)
        os.killpg(pgid, signal.SIGINT)
        try:
            self._proc.wait(timeout=5)
        except subprocess.TimeoutExpired:
            os.killpg(pgid, signal.SIGKILL)
            self._proc.wait(timeout=5)
        self._proc = None
        self.transport = None

    def restart(self, transport_label):
        self.stop()
        self.start(transport_label)


class TrialSession:
    """One participant/study's trial plan, read once from the workbook, plus
    the recording state machine (atomic lock + SIGINT-then-SIGKILL, same
    approach as pilot_trial_runner.py)."""

    def __init__(self, cmds, participant, study, excel_path, relay, transport_label_getter):
        if study not in STUDY_SHEET:
            raise ValueError(f'study must be 1 or 2, got {study!r}')
        self.cmds = cmds
        self.participant = participant
        self.study = study
        self.sheet_name = STUDY_SHEET[study]
        self.excel_path = excel_path
        self.relay = relay
        self.transport_label_getter = transport_label_getter

        wb = openpyxl.load_workbook(self.excel_path, data_only=True)
        ws = wb[self.sheet_name]
        self.rows = []
        for r in range(2, ws.max_row + 1):
            if ws.cell(r, COL_PARTICIPANT).value != participant:
                continue
            trial_num = ws.cell(r, COL_TRIAL_NUM).value             # int, or "Warm-up"
            mode_code = ws.cell(r, COL_MODE_CODE).value              # None for Warm-up
            self.rows.append({
                'row': r,
                'trial_num': trial_num,
                'mode_name': ws.cell(r, COL_MODE_NAME).value,
                'mode_code': mode_code,
                'setup_info': ws.cell(r, COL_SETUP_INFO).value,
                'stem': _make_stem(participant, study, mode_code, trial_num),
                'done': bool(ws.cell(r, COL_COMPLETED).value),
            })
        if not self.rows:
            raise RuntimeError(f'no rows found for participant {participant!r} in {self.sheet_name}')

        self.index = 0
        self._recording = None
        self._bag_path = None
        self._lock_path = None

    # -- sequence -----------------------------------------------------------

    def current(self):
        if self.index >= len(self.rows):
            return None
        return self.rows[self.index]

    def advance(self):
        if self.index < len(self.rows):
            self.index += 1

    # -- mode -----------------------------------------------------------

    def set_mode_for_current(self):
        info = self.current()
        if info is None or info['mode_code'] is None:
            return  # Warm-up rows have no preset mode -- pick one by hand
        teleop_mode, do_on = STUDY_CONDITIONS[info['mode_code']]
        result = self.cmds['set_mode'].Execute(mtsStdString(teleop_mode), MTS_NOT_BLOCKING)
        if not result.IsOK():
            raise RuntimeError(f'set_teleop_mode({teleop_mode!r}) failed: {result}')
        time.sleep(0.1)
        self.cmds['set_psm_do'].Execute(mtsBool(do_on), MTS_NOT_BLOCKING)
        self.cmds['set_mtm_do'].Execute(mtsBool(do_on), MTS_NOT_BLOCKING)
        actual = _read_mode(self.cmds)
        if actual == '(unknown)':
            # can't parse the read-back in this binding -- the write itself
            # already reported IsOK() above, which is real evidence the
            # mode switched; don't block the trial on an unrelated Python
            # API gap, just say so
            print(f'study_gui: could not verify teleop_mode read-back for {teleop_mode!r}; '
                  f'trusting the write (result.IsOK() above)')
        elif actual != teleop_mode:
            raise RuntimeError(
                f'teleop_mode verify failed: requested {teleop_mode!r}, read back {actual!r}. '
                f'Not starting the trial in an unverified mode.'
            )

    # -- rosbag -----------------------------------------------------------

    def _bag_path_for(self, info):
        out_dir = os.path.join(DATA_ROOT, self.participant, f'study{self.study}')
        return os.path.join(out_dir, info['stem'])

    def start_trial(self):
        if self._recording is not None:
            raise RuntimeError('a trial is already recording -- stop or abort it first')
        info = self.current()
        if info is None:
            raise RuntimeError('no more trials in this session')

        self.set_mode_for_current()

        bag_path = self._bag_path_for(info)
        os.makedirs(os.path.dirname(bag_path), exist_ok=True)

        lock_path = bag_path + '.lock'
        try:
            fd = os.open(lock_path, os.O_CREAT | os.O_EXCL | os.O_WRONLY)
            os.close(fd)
        except FileExistsError:
            raise RuntimeError(f'{lock_path} exists -- already recording (or a stale lock; remove it by hand if so)')
        self._lock_path = lock_path

        if os.path.exists(bag_path):
            os.remove(lock_path)
            self._lock_path = None
            raise RuntimeError(f'{bag_path} already exists -- use "Redo trial" to delete it first')

        cmd = ['ros2', 'bag', 'record', '-o', bag_path] + TOPICS
        self._recording = subprocess.Popen(cmd, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                                            stderr=subprocess.PIPE, preexec_fn=os.setsid)
        self._bag_path = bag_path

        # bag record first, THEN restart the video relay -- order matters.
        # The relay's encoder emits its header/setup packets exactly once,
        # right at startup, and DDS won't redeliver them to a subscriber
        # that wasn't matched yet (VOLATILE durability, confirmed). Starting
        # the recorder's subscription first and giving it a moment to be
        # discovered means the encoder's startup -- headers included --
        # happens only after the recorder is already listening, so this
        # trial's own bag actually captures them. Doing it the other way
        # round (or not restarting at all) is exactly how P01_S2_BIL_T02/
        # T04/UNI_T03 ended up with headerless, undecodable video.
        time.sleep(1.0)
        self.relay.restart(self.transport_label_getter())
        return bag_path

    def _stop_process(self, proc):
        pgid = os.getpgid(proc.pid)
        os.killpg(pgid, signal.SIGINT)   # clean EOS, not SIGKILL
        try:
            # mcap only writes its summary/chunk-index on a clean exit --
            # SIGKILL truncates mid-write and leaves a bag that needs
            # `ros2 bag reindex` to even be readable. 10s used to be enough
            # before this recorded video too; with theora/jpeg in the mix
            # (larger buffers to flush) plus this machine's typical load,
            # a clean SIGINT exit can genuinely take longer than that even
            # though it's not stuck -- found the hard way (this call used
            # to time out into SIGKILL under exactly those conditions,
            # which is why trials kept coming out needing a reindex).
            proc.wait(timeout=30)
        except subprocess.TimeoutExpired:
            os.killpg(pgid, signal.SIGKILL)
            proc.wait(timeout=5)

    def _release_lock(self):
        if self._lock_path and os.path.exists(self._lock_path):
            os.remove(self._lock_path)
        self._lock_path = None

    def stop_trial(self):
        if self._recording is None:
            return None
        self._stop_process(self._recording)
        self._recording = None
        self._release_lock()

        info = self.current()
        path = self._bag_path
        self._bag_path = None
        self._log_to_excel(info, path)
        info['done'] = True
        return path

    def abort_trial(self):
        """False start while actively recording: stop and delete."""
        if self._recording is None:
            return
        self._stop_process(self._recording)
        self._recording = None
        self._release_lock()
        if self._bag_path and os.path.isdir(self._bag_path):
            shutil.rmtree(self._bag_path)
        self._bag_path = None

    def redo_trial(self):
        """Delete an already-completed current trial's bag + clear its Excel
        log so start_trial() can be called again for the same slot.

        Gated on whether the bag actually exists on disk, not on the
        in-memory `done` flag -- that flag only reflects the workbook as it
        was at "Load session" time (or updated by this same session's own
        stop_trial()), so it goes stale if the trial was actually recorded
        by an earlier/different session and this one was never reloaded.
        The filesystem is ground truth for "is there something to delete".
        """
        if self._recording is not None:
            raise RuntimeError('currently recording -- abort it first, not redo')
        info = self.current()
        if info is None:
            raise RuntimeError('no current trial to redo')
        bag_path = self._bag_path_for(info)
        if not os.path.isdir(bag_path):
            raise RuntimeError(
                f'no recording found on disk at {bag_path} -- nothing to redo. '
                f'If you believe this trial was actually recorded, the loaded '
                f'session may be stale -- try "Load session" again.'
            )
        shutil.rmtree(bag_path)
        self._clear_excel(info)
        info['done'] = False

    # -- excel -----------------------------------------------------------

    def _log_to_excel(self, info, bag_path):
        wb = openpyxl.load_workbook(self.excel_path)
        ws = wb[self.sheet_name]
        headers = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
        for header in (BAG_PATH_COL_HEADER, RECORDED_AT_COL_HEADER):
            if header not in headers:
                ws.cell(1, ws.max_column + 1, header)
                headers.append(header)
        bag_col = headers.index(BAG_PATH_COL_HEADER) + 1
        recorded_col = headers.index(RECORDED_AT_COL_HEADER) + 1
        ws.cell(info['row'], COL_COMPLETED, True)
        ws.cell(info['row'], bag_col, bag_path)
        ws.cell(info['row'], recorded_col, datetime.datetime.now(datetime.timezone.utc).isoformat())
        wb.save(self.excel_path)

    def _clear_excel(self, info):
        wb = openpyxl.load_workbook(self.excel_path)
        ws = wb[self.sheet_name]
        headers = [ws.cell(1, c).value for c in range(1, ws.max_column + 1)]
        ws.cell(info['row'], COL_COMPLETED, None)
        for col in OUTCOME_COLUMNS:
            ws.cell(info['row'], col, None)
        for header in (BAG_PATH_COL_HEADER, RECORDED_AT_COL_HEADER):
            if header in headers:
                ws.cell(info['row'], headers.index(header) + 1, None)
        wb.save(self.excel_path)


def launch():
    cmds = _connect()

    root = tk.Tk()
    root.title(f'{COMPONENT_NAME} study control')

    # -- mode switching -----------------------------------------------------

    mode_frame = ttk.LabelFrame(root, text='teleop_mode')
    mode_frame.pack(padx=10, pady=10, fill='x')

    current_mode = tk.StringVar(value=_read_mode(cmds))
    ttk.Label(mode_frame, text='current:').grid(row=0, column=0, sticky='w', padx=(5, 0))
    ttk.Label(mode_frame, textvariable=current_mode, font=('', 11, 'bold')).grid(row=0, column=1, sticky='w', padx=(2, 15))

    def set_condition(code):
        teleop_mode, do_on = STUDY_CONDITIONS[code]
        cmds['set_mode'].Execute(mtsStdString(teleop_mode), MTS_NOT_BLOCKING)
        psm_do.set(do_on)
        toggle_psm_do()
        mtm_do.set(do_on)
        toggle_mtm_do()
        # display the CODE (e.g. "BIL_ON"), not the raw teleop_mode --
        # BIL_ON/BIL_OFF both report back as plain "bilateral" from the
        # robot, so the code is the only thing that actually distinguishes
        # them; refresh_mode() below can't reconstruct this from a
        # hardware read-back
        current_mode.set(code)

    big_style = ttk.Style()
    big_style.configure('Big.TButton', font=('', 13, 'bold'), padding=10)

    main_row = ttk.Frame(mode_frame)
    main_row.grid(row=1, column=0, columnspan=4, pady=(5, 5))
    for code in STUDY_CONDITIONS:
        ttk.Button(main_row, text=code, style='Big.TButton', width=14,
                   command=lambda c=code: set_condition(c)).pack(side='left', padx=5)

    other_row = ttk.Frame(mode_frame)
    other_row.grid(row=2, column=0, columnspan=4, pady=(0, 5))

    def refresh_mode():
        mode = _read_mode(cmds)
        # "bilateral" alone is ambiguous now -- it's what BOTH BIL_ON and
        # BIL_OFF report back as
        if mode == 'bilateral':
            mode += ' (DOBS on/off ambiguous from hardware read-back -- check DO checkboxes below)'
        current_mode.set(mode)

    ttk.Button(other_row, text='refresh', command=refresh_mode).pack(side='left', padx=2)

    # -- disturbance observer -------------------------------------------------

    do_frame = ttk.LabelFrame(root, text='disturbance observer (PID, live)')
    do_frame.pack(padx=10, pady=(0, 10), fill='x')

    psm_do = tk.BooleanVar(value=False)
    mtm_do = tk.BooleanVar(value=False)

    def toggle_psm_do():
        cmds['set_psm_do'].Execute(mtsBool(psm_do.get()), MTS_NOT_BLOCKING)

    def toggle_mtm_do():
        cmds['set_mtm_do'].Execute(mtsBool(mtm_do.get()), MTS_NOT_BLOCKING)

    ttk.Checkbutton(do_frame, text='PSM DO on', variable=psm_do, command=toggle_psm_do).pack(side='left', padx=10, pady=5)
    ttk.Checkbutton(do_frame, text='MTM DO on', variable=mtm_do, command=toggle_mtm_do).pack(side='left', padx=10, pady=5)
    ttk.Label(
        do_frame,
        text='write-only -- reflects the last click, not a live PID read-back (see console for confirmation)',
        foreground='gray',
    ).pack(side='left', padx=10)

    # -- video relay -------------------------------------------------------

    video_frame = ttk.LabelFrame(root, text='compressed video relay')
    video_frame.pack(padx=10, pady=(0, 10), fill='x')

    relay = VideoRelay()
    video_status = tk.StringVar(value='stopped')
    video_transport = tk.StringVar(value=DEFAULT_VIDEO_TRANSPORT)

    transport_menu = ttk.Combobox(video_frame, textvariable=video_transport,
                                   values=list(VIDEO_TRANSPORTS.keys()), state='readonly', width=24)
    transport_menu.pack(side='left', padx=(10, 5), pady=5)

    def toggle_video_relay():
        if relay.running():
            relay.stop()
            transport_menu.state(['!disabled'])
        else:
            try:
                relay.start(video_transport.get())
                transport_menu.state(['disabled'])  # switching codec mid-relay needs stop/start anyway
            except Exception as exc:
                messagebox.showerror('Video relay failed to start', str(exc))
        video_status.set('running' if relay.running() else 'stopped')

    ttk.Button(video_frame, text='Start/Stop relay', command=toggle_video_relay).pack(side='left', padx=5, pady=5)
    ttk.Label(video_frame, textvariable=video_status, font=('', 10, 'bold')).pack(side='left', padx=(0, 15))
    ttk.Label(
        video_frame,
        text=(f'Subscribes {RAW_VIDEO_TOPIC} (start dvrk_video/gscam yourself, separately),\n'
              f'republishes on the chosen transport\'s topic -- both are already in every trial\'s TOPICS list.'),
        foreground='gray', justify='left',
    ).pack(side='left')

    # -- trial session --------------------------------------------------------

    trial_frame = ttk.LabelFrame(root, text='pilot trial session')
    trial_frame.pack(padx=10, pady=(0, 10), fill='x')

    session = {'obj': None}

    excel_row = ttk.Frame(trial_frame)
    excel_row.pack(fill='x', padx=5, pady=(5, 0))
    ttk.Label(excel_row, text='Excel:').pack(side='left')
    excel_path_var = tk.StringVar(value=EXCEL_PATH)
    ttk.Entry(excel_row, textvariable=excel_path_var, width=55).pack(side='left', padx=(2, 5))

    def browse_excel():
        path = filedialog.askopenfilename(
            title='Select pilot tracking workbook',
            initialdir=os.path.dirname(excel_path_var.get()) or '.',
            filetypes=[('Excel workbook', '*.xlsx'), ('All files', '*.*')],
        )
        if path:
            excel_path_var.set(path)

    ttk.Button(excel_row, text='Browse...', command=browse_excel).pack(side='left')

    setup_row = ttk.Frame(trial_frame)
    setup_row.pack(fill='x', padx=5, pady=5)
    ttk.Label(setup_row, text='Participant:').pack(side='left')
    participant_var = tk.StringVar(value='P01')
    ttk.Entry(setup_row, textvariable=participant_var, width=8).pack(side='left', padx=(2, 15))
    ttk.Label(setup_row, text='Study:').pack(side='left')
    study_var = tk.IntVar(value=1)
    ttk.Radiobutton(setup_row, text='1 - Palpation', variable=study_var, value=1).pack(side='left')
    ttk.Radiobutton(setup_row, text='2 - Peg Transfer', variable=study_var, value=2).pack(side='left')

    status_var = tk.StringVar(value='(no session loaded)')
    ttk.Label(trial_frame, textvariable=status_var, font=('', 11, 'bold'), justify='left').pack(
        anchor='w', padx=5, pady=(0, 5))

    def refresh_status():
        obj = session['obj']
        if obj is None:
            status_var.set('(no session loaded)')
            return
        info = obj.current()
        if info is None:
            status_var.set(f'{obj.participant} / study {obj.study}: all trials complete.')
            return
        label = SETUP_INFO_LABEL[obj.study]
        setup = info['setup_info'] if info['setup_info'] is not None else 'n/a'
        mode = info['mode_code'] or '(select manually -- Warm-up)'
        done = ' [ALREADY RECORDED]' if info['done'] else ''
        status_var.set(
            f"{obj.participant} / study {obj.study}  --  trial {obj.index + 1}/{len(obj.rows)}{done}\n"
            f"trial #: {info['trial_num']}   mode: {mode}\n"
            f"{label}: {setup}\n"
            f"rosbag stem: {info['stem']}"
        )

    def apply_current_mode():
        # pushes the current trial's mode + DO policy to the robot right
        # away, so "current:" above and the robot's actual state match
        # whatever the trial panel is showing -- without this, loading a
        # session or moving to the next trial only updated the display,
        # leaving the robot on whatever mode/DO was previously active until
        # Start was clicked
        obj = session['obj']
        if obj is None:
            return
        try:
            obj.set_mode_for_current()
            refresh_mode()
        except Exception as exc:
            messagebox.showerror('Mode switch failed', str(exc))

    def load_session():
        try:
            session['obj'] = TrialSession(cmds, participant_var.get().strip(), study_var.get(),
                                           excel_path_var.get().strip(), relay, video_transport.get)
        except Exception as exc:
            messagebox.showerror('Load session failed', str(exc))
            return
        refresh_status()
        apply_current_mode()

    ttk.Button(setup_row, text='Load session', command=load_session).pack(side='left', padx=(15, 0))

    def run_async(work_fn, on_success=None, on_error=None, busy_widgets=()):
        # stop_trial()/abort_trial() send SIGINT then block waiting for
        # `ros2 bag record` to exit (now up to 30s, see _stop_process) --
        # doing that directly in a button's command callback blocks
        # Tkinter's own event loop for the whole wait, freezing the entire
        # window (this was the "GUI keeps freezing" symptom). Runs work_fn
        # on a worker thread instead and polls for completion via
        # root.after() -- Tkinter itself isn't thread-safe, so on_success/
        # on_error/re-enabling busy_widgets all happen back on the main
        # thread from that poll, never from the worker thread directly.
        for w in busy_widgets:
            w.state(['disabled'])
        result = {}

        def worker():
            try:
                result['value'] = work_fn()
            except Exception as exc:
                result['error'] = exc

        threading.Thread(target=worker, daemon=True).start()

        def poll():
            if 'value' not in result and 'error' not in result:
                root.after(150, poll)
                return
            for w in busy_widgets:
                w.state(['!disabled'])
            if 'error' in result:
                (on_error or (lambda exc: messagebox.showerror('Error', str(exc))))(result['error'])
            elif on_success:
                on_success(result.get('value'))

        root.after(150, poll)

    button_row = ttk.Frame(trial_frame)
    button_row.pack(fill='x', padx=5, pady=(0, 8))

    def start_trial():
        obj = session['obj']
        if obj is None:
            return
        try:
            path = obj.start_trial()
            # start_trial() restarts the video relay itself (fresh headers
            # per trial, see TrialSession.start_trial()) -- reflect that
            # here rather than leaving the dropdown/status showing whatever
            # was true before this trial started
            video_status.set('running' if relay.running() else 'stopped')
            transport_menu.state(['disabled'] if relay.running() else ['!disabled'])
            messagebox.showinfo('Recording', f'Recording -> {path}\n\nRun the trial, then Stop.')
            refresh_status()
        except Exception as exc:
            messagebox.showerror('Start trial failed', str(exc))

    def stop_trial():
        obj = session['obj']
        if obj is None:
            return
        status_var.set('Stopping recording, waiting for the bag to finalize -- please wait...')

        def on_success(path):
            if path:
                messagebox.showinfo('Saved', f'Saved and logged:\n{path}')
            refresh_status()

        def on_error(exc):
            messagebox.showerror('Stop trial failed', str(exc))
            refresh_status()

        run_async(obj.stop_trial, on_success, on_error, busy_widgets=trial_buttons)

    def abort_trial():
        obj = session['obj']
        if obj is None:
            return
        if not messagebox.askyesno('Abort trial', 'Stop recording and DELETE this rosbag (false start)?'):
            return
        status_var.set('Stopping recording (abort) -- please wait...')

        def on_success(_):
            refresh_status()

        def on_error(exc):
            messagebox.showerror('Abort trial failed', str(exc))
            refresh_status()

        run_async(obj.abort_trial, on_success, on_error, busy_widgets=trial_buttons)

    def redo_trial():
        obj = session['obj']
        if obj is None:
            return
        if not messagebox.askyesno(
            'Redo trial',
            'DELETE the existing rosbag for this trial and clear its Excel row '
            '(Completed, bag path, and any outcome data -- contact force, '
            'completion time / dropped pegs, TLX-adjacent notes, etc.) so it '
            'can be re-recorded?'
        ):
            return
        try:
            obj.redo_trial()
            refresh_status()
        except Exception as exc:
            messagebox.showerror('Redo trial failed', str(exc))

    def next_trial():
        obj = session['obj']
        if obj is None:
            return
        info = obj.current()
        if info is not None and not info['done']:
            if not messagebox.askyesno('Next trial', 'This trial has not been recorded yet -- advance anyway?'):
                return
        else:
            if not messagebox.askyesno('Next trial', 'Move on to the next trial?'):
                return
        obj.advance()
        refresh_status()
        apply_current_mode()

    btn_start = ttk.Button(button_row, text='Start trial', command=start_trial)
    btn_stop = ttk.Button(button_row, text='Stop trial', command=stop_trial)
    btn_abort = ttk.Button(button_row, text='Abort (false start)', command=abort_trial)
    btn_redo = ttk.Button(button_row, text='Redo trial', command=redo_trial)
    btn_next = ttk.Button(button_row, text='Next trial →', command=next_trial)
    btn_start.pack(side='left', padx=3)
    btn_stop.pack(side='left', padx=3)
    btn_abort.pack(side='left', padx=3)
    btn_redo.pack(side='left', padx=3)
    btn_next.pack(side='left', padx=(15, 3))
    # disabled (all of them, to avoid overlapping actions) while stop_trial()/
    # abort_trial() are waiting in the background for `ros2 bag record` to
    # exit -- see run_async()
    trial_buttons = [btn_start, btn_stop, btn_abort, btn_redo, btn_next]

    ttk.Label(
        trial_frame,
        text=('Start trial restarts the video relay itself, fresh, for every trial (needed so '
              'theora/jpeg headers land inside that trial\'s own bag -- see VideoRelay docstring).\n'
              '(dvrk_video/gscam itself still needs to be started separately, by hand.)\n'
              'Close "Pilot_Study.xlsx" while running a session (see file header comment).'),
        foreground='gray', justify='left',
    ).pack(anchor='w', padx=5, pady=(0, 8))

    def on_close():
        relay.stop()
        root.destroy()

    root.protocol('WM_DELETE_WINDOW', on_close)
    root.mainloop()


threading.Thread(target=launch, daemon=True).start()
